### ISSUE TITLE
undefined envdir ENDAGA_BASE_PATH

### ISSUE THREAD

**Issue by eprueves** [pcarivbts/CommunityCellularManager#3]
in aricent-phase1 branch: 
undefined envdir ENDAGA_BASE_PATH in https://github.com/pcarivbts/CommunityCellularManager/blob/aricent-phase1/cloud/endagaweb/settings/prod.py#L353

This should be included in endagaweb/envdir
@cereblanco , what is the value that you used here? 
```
python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/cloud/endagaweb/__init__.py", line 14, in <module>
    from .celery import app as celery_app  # noqa: F401 (unused import)
  File "/home/vagrant/cloud/endagaweb/celery.py", line 28, in <module>
    app.conf.update(CELERYBEAT_SCHEDULE={
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/base.py", line 630, in conf
    return self._get_config()
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/base.py", line 454, in _get_config
    self.loader.config_from_object(self._config_source)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/loaders/base.py", line 145, in config_from_object
    self._conf = force_mapping(obj)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/datastructures.py", line 52, in force_mapping
    return DictAttribute(m) if not isinstance(m, Mapping) else m
  File "/home/vagrant/.virtualenvs/endaga/lib/python2.7/abc.py", line 131, in __instancecheck__
    subclass = getattr(instance, '__class__', None)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/utils/functional.py", line 234, in inner
    self._setup()
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/cloud/endagaweb/settings/dev.py", line 23, in <module>
    from .staff import *
  File "/home/vagrant/cloud/endagaweb/settings/staff.py", line 23, in <module>
    from .prod import *
  File "/home/vagrant/cloud/endagaweb/settings/prod.py", line 353, in <module>
    os.path.join(os.environ["ENDAGA_BASE_PATH"], 'locale'),
  File "/home/vagrant/.virtualenvs/endaga/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'ENDAGA_BASE_PATH'

````

**Comment by cereblanco** [comment]
path to your endaga folder

**Comment by eprueves** [comment]
This is for the message files for i18n/l10n?
