### ISSUE TITLE
fake_phone_client not working in py3

### ISSUE THREAD

**Issue by eprueves** [pcarivbts/CommunityCellularManager#7]
```
fake_phone_client 
Traceback (most recent call last):

  File "/usr/local/bin/fake_phone_client", line 39, in <module>
    from core.fake_phone import FakePhone
  File "/usr/local/lib/python3.4/dist-packages/core/fake_phone/__init__.py", line 20, in <module>
    from . import _openbts
  File "/usr/local/lib/python3.4/dist-packages/core/fake_phone/_openbts.py", line 18, in <module>
    from twisted.internet import reactor
ImportError: No module named 'twisted'
```

to fix, need to install swig: sudo apt-get install swig
and the ff packages via pip

Twisted==17.9.0
python-ESL==1.4.18

will be confirming functionality after this.

**Comment by eprueves** [comment]
More errors: @cereblanco, did you get this one?

```
vagrant@endaga-client-openbts:~$ fake_phone_client IMSI001010000000099
RESPONSE: 404
sms 101 t
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/lib/python3.4/dist-packages/core/fake_phone/_openbts.py", line 103, in sendSMS
    content = sms_utilities.SMS_Submit.gen_msg(str(dest), content, False)
  File "/usr/local/lib/python3.4/dist-packages/sms_utilities/SMS_Submit.py", line 44, in gen_msg
    rp_header = gen_rp_header(ref, empty)
  File "/usr/local/lib/python3.4/dist-packages/sms_utilities/SMS_Submit.py", line 36, in gen_rp_header
    SMS_Helper.encode_num("0000")  # RP-destination address
  File "/usr/local/lib/python3.4/dist-packages/sms_utilities/SMS_Helper.py", line 36, in encode_num
    "81" +
  File "/usr/local/lib/python3.4/dist-packages/sms_utilities/SMS_Helper.py", line 17, in to_hex2
    tmp = hex(i)[2:]
builtins.TypeError: 'float' object cannot be interpreted as an integer


```
